# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koolack_unscaled', '0002_auto_20160331_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kool',
            old_name='contents',
            new_name='content',
        ),
    ]
